---
stages:
- name: "Build and push docker image"
  steps:
  - env:
      PLUGIN_BUILD_ARGS: "--progress=tty --network=host"
      PLUGIN_DEBUG: true
      PLUGIN_INSECURE: true
      PLUGIN_MIRROR: "https://harbor-dev.iiidevops.org"
      PLUGIN_MTU: 1000
    publishImageConfig:
      dockerfilePath: "./Dockerfile"
      buildContext: "."
      tag: "${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest"
      pushRemote: true
      registry: "harbor-dev.iiidevops.org"
    when:
      branch:
        include:
        - "master"
        - "develop"
- name: "Checkmarx source code scan"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-scan-checkmarx"
      version: "0.1.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-cmx"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        pipeline.sequence: "${CICD_EXECUTION_SEQUENCE}"
    when:
      branch:
        include:
        - "master"
        - "checkmarx"
- name: "Deploy app-webserver"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-web"
      version: "0.5.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        harbor.host: "harbor-dev.iiidevops.org"
        web.imageTag: "${CICD_GIT_REPO_NAME}/${CICD_GIT_BRANCH}:latest"
        web.port: 3000
    when:
      branch:
        include:
        - "master"
        - "develop"
- name: "Wait web deployment"
  steps:
  - runScriptConfig:
      image: "iiiorg/deployment-waiter:0.0.2"
      shellScript: "rancher login ${rancher_url} -t ${rancher_api_token} --skip-verify;\n\
        bash /app/run.sh;"
    env:
      deploy_name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web"
      max_wait: 128
      namespace: "${CICD_GIT_REPO_NAME}"
    envFrom:
    - sourceKey: "API_TOKEN"
      sourceName: "pipeline-api-key"
      targetKey: "rancher_api_token"
    - sourceKey: "rancher-url"
      sourceName: "rancher"
      targetKey: "rancher_url"
    when:
      branch:
        include:
        - "master"
        - "develop"
- name: "Postman test"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-test-postman"
      version: "0.1.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-pm"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        pipeline.sequence: "${CICD_EXECUTION_SEQUENCE}"
        web.deployName: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web"
        web.port: 3000
    when:
      branch:
        include:
        - "master"
- name: "Webinspect test"
  steps:
  - applyAppConfig:
      catalogTemplate: "cattle-global-data:iii-dev-charts3-test-webinspect"
      version: "0.1.0"
      name: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-wi"
      targetNamespace: "${CICD_GIT_REPO_NAME}"
      answers:
        git.branch: "${CICD_GIT_BRANCH}"
        git.commitID: "${CICD_GIT_COMMIT}"
        git.repoName: "${CICD_GIT_REPO_NAME}"
        git.url: "${CICD_GIT_URL}"
        pipeline.sequence: "${CICD_EXECUTION_SEQUENCE}"
        web.deployName: "${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-web"
    when:
      branch:
        include:
        - "master"
